import { contextBridge, ipcRenderer } from 'electron'
import type { DefinitionSpec, LivePort } from '@shared/types'
import type { McpAddInput } from '@shared/mcp'
import type { BurpSettings } from '@shared/capture'

const api = {
  prereqCheck: () => ipcRenderer.invoke('prereq:check'),
  instancesList: () => ipcRenderer.invoke('instances:list'),
  defCreate: (spec: DefinitionSpec) => ipcRenderer.invoke('def:create', spec),
  defUpdate: (spec: DefinitionSpec) => ipcRenderer.invoke('def:update', spec),
  defGetSpec: (id: string) => ipcRenderer.invoke('def:getSpec', id),
  defExport: (ids: string[]) => ipcRenderer.invoke('def:export', ids),
  defImport: () => ipcRenderer.invoke('def:import'),
  defRemove: (id: string) => ipcRenderer.invoke('def:remove', id),
  defList: () => ipcRenderer.invoke('def:list'),
  pickFolder: () => ipcRenderer.invoke('dialog:pickFolder'),
  pickFile: () => ipcRenderer.invoke('dialog:pickFile'),
  instanceLaunch: (definitionId: string, name?: string, opener?: 'terminal' | 'vscode', tags?: string[]) => ipcRenderer.invoke('instance:launch', definitionId, name, opener, tags),
  instanceAttach: (name: string, opener?: 'terminal' | 'vscode') => ipcRenderer.invoke('instance:attach', name, opener),
  instanceRebuild: (name: string, opener?: 'terminal' | 'vscode', preserveSessions?: boolean) => ipcRenderer.invoke('instance:rebuild', name, opener, preserveSessions),
  instanceApplyCredentials: (name: string) => ipcRenderer.invoke('instance:applyCredentials', name),
  instanceCommands: (name: string) => ipcRenderer.invoke('instance:commands', name),
  instanceShell: (name: string) => ipcRenderer.invoke('instance:shell', name),
  instanceStop: (name: string) => ipcRenderer.invoke('instance:stop', name),
  instanceRemove: (name: string) => ipcRenderer.invoke('instance:remove', name),
  instanceSetTags: (name: string, tags: string[]) => ipcRenderer.invoke('instance:setTags', name, tags),
  secretListGlobal: () => ipcRenderer.invoke('secret:listGlobal'),
  secretSetGlobal: (serviceId: string, value: string) => ipcRenderer.invoke('secret:setGlobal', serviceId, value),
  secretSetGlobalFromEnv: (serviceId: string) => ipcRenderer.invoke('secret:setGlobalFromEnv', serviceId),
  secretRemoveGlobal: (id: string) => ipcRenderer.invoke('secret:removeGlobal', id),
  credScanEnv: () => ipcRenderer.invoke('cred:scanEnv'),
  credStageValue: (key: string, value: string) => ipcRenderer.invoke('cred:stageValue', key, value),
  credStageFromEnv: (key: string, serviceId: string) => ipcRenderer.invoke('cred:stageFromEnv', key, serviceId),
  instancePortsList: (name: string) => ipcRenderer.invoke('instance:ports:list', name),
  instancePortsPublish: (name: string, port: LivePort) => ipcRenderer.invoke('instance:ports:publish', name, port),
  instancePortsUnpublish: (name: string, port: LivePort) => ipcRenderer.invoke('instance:ports:unpublish', name, port),
  instanceHostServiceAdd: (name: string, hostPort: number, label: string) => ipcRenderer.invoke('instance:hostService:add', name, hostPort, label),
  instanceHostServiceRemove: (name: string, hostPort: number) => ipcRenderer.invoke('instance:hostService:remove', name, hostPort),
  instanceDomainAllow: (name: string, domain: string) => ipcRenderer.invoke('instance:domain:allow', name, domain),
  instanceDomainDeny: (name: string, domain: string) => ipcRenderer.invoke('instance:domain:deny', name, domain),
  instancePolicyLog: (name: string) => ipcRenderer.invoke('instance:policyLog', name),
  instanceStats: (name: string) => ipcRenderer.invoke('instance:stats', name),
  instanceFsListDir: (name: string, path: string) => ipcRenderer.invoke('instance:fs:listDir', name, path),
  instanceFsPlan: (name: string, direction: string, sources: string[], dest: string, defaults: { host: string; sandbox: string }) => ipcRenderer.invoke('instance:fs:plan', name, direction, sources, dest, defaults),
  instanceFsCopy: (name: string, direction: string, sources: string[], dest: string) => ipcRenderer.invoke('instance:fs:copy', name, direction, sources, dest),
  pickPaths: (mode: 'files' | 'folder') => ipcRenderer.invoke('dialog:pickPaths', mode),
  authStatus: () => ipcRenderer.invoke('auth:status'),
  authSignOut: () => ipcRenderer.invoke('auth:signOut'),
  authStartLogin: () => ipcRenderer.invoke('auth:startLogin'),
  sshDetect: () => ipcRenderer.invoke('ssh:detect'),
  hostCapacity: () => ipcRenderer.invoke('host:capacity'),
  envHasVSCode: () => ipcRenderer.invoke('env:hasVSCode'),
  kitValidate: (yaml: string) => ipcRenderer.invoke('kit:validate', yaml),
  prefsGet: (key: string) => ipcRenderer.invoke('prefs:get', key),
  prefsSet: (key: string, value: string) => ipcRenderer.invoke('prefs:set', key, value),
  credsStorageStatus: () => ipcRenderer.invoke('creds:storageStatus'),
  mcpSupported: () => ipcRenderer.invoke('mcp:supported'),
  mcpList: () => ipcRenderer.invoke('mcp:list'),
  mcpInspect: (name: string) => ipcRenderer.invoke('mcp:inspect', name),
  mcpAdd: (input: McpAddInput) => ipcRenderer.invoke('mcp:add', input),
  mcpRemove: (name: string) => ipcRenderer.invoke('mcp:remove', name),
  mcpAuthStatus: (name: string) => ipcRenderer.invoke('mcp:authStatus', name),
  mcpStartAuth: (name: string) => ipcRenderer.invoke('mcp:startAuth', name),
  mcpSetClientSecret: (name: string, value: string) => ipcRenderer.invoke('mcp:setClientSecret', name, value),
  mcpRemoveAuth: (name: string) => ipcRenderer.invoke('mcp:removeAuth', name),
  captureStatus: () => ipcRenderer.invoke('capture:status'),
  captureEnable: (name: string, force = false) => ipcRenderer.invoke('capture:enable', name, force),
  captureDisable: () => ipcRenderer.invoke('capture:disable'),
  captureSettingsGet: () => ipcRenderer.invoke('capture:settingsGet'),
  captureSettingsSet: (patch: Partial<BurpSettings>) => ipcRenderer.invoke('capture:settingsSet', patch),
  captureCaInspect: (path: string) => ipcRenderer.invoke('capture:caInspect', path),
  captureBurpConfig: () => ipcRenderer.invoke('capture:burpConfig'),
  captureExportConfig: () => ipcRenderer.invoke('capture:exportConfig'),
  sessionListArchives: (name: string) => ipcRenderer.invoke('session:listArchives', name),
  sessionExportArchive: (dir: string) => ipcRenderer.invoke('session:exportArchive', dir),
  setTitleBarOverlay: (light: boolean) => ipcRenderer.send('theme:setOverlay', light)
}

contextBridge.exposeInMainWorld('api', api)

export type Api = typeof api
